root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = [
    "--listen=0.0.0.0:2345",
    "--headless",
    "--continue",
    "--accept-multiclient",
    "--",
    "server",
  ]
#  bin = "./tmp/main"
  full_bin = "dlv exec ./tmp/main"
#  cmd = "go build -o ./tmp/main ."
  cmd = "go build -gcflags=\"all=-N -l\" -o ./tmp/main ."
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
#  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
#  stop_on_error = true
  stop_on_error = false
  poll = true # Poll files for changes instead of using fsnotify (fsnotify in Windows not working).
  rerun = false
  rerun_delay = 500

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
