include:
    - infra/keycloak/docker-compose.yml
    - infra/kafka/docker-compose.yml
    - infra/swagger/docker-compose.yml
    - infra/jaeger/docker-compose.yml
    - backend/dictionary/docker-compose.yml
    - backend/exercise/docker-compose.yml
    - backend/analytics/docker-compose.yml

services:
    lcg-traefik:
        image: traefik:3.2.3
        command:
            --api.insecure=true
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.web.address=:80
            --entryPoints.web-debug.address=:2345
            --entryPoints.dictionary-db.address=:54321
            --entryPoints.exercise-db.address=:54322
            --entryPoints.analytics-db.address=:59000
            --entryPoints.dictionary-grpc.address=:50051
        ports:
            - "80:80"
            - "2345:2345" # golang delve debug
            - "54321:54321" # dictionary-db
            - "54322:54322" # exercise-db
            - "59000:59000" # analytics-db
            - "8080:8080" # traefik dashboard
            - "50051:50051" # dictionary-grpc
        secrets:
            - jaeger_ui_password
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            # cors для http://swagger.lingua-cat-go.localhost/
            - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Origin=*
            - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Methods=*
            - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Headers=*

secrets:
    keycloak_db_password:
        file: ./docker/secrets/backend_keycloak_db_password
    dictionary_db_password:
        file: ./docker/secrets/backend_dictionary_db_password
    exercise_db_password:
        file: ./docker/secrets/backend_exercise_db_password
    analytics_db_password:
        file: ./docker/secrets/backend_analytics_db_password
    auth_public_key:
        file: ./docker/secrets/backend_auth_public_key
    jaeger_ui_password:
        file: ./docker/secrets/backend_jaeger_ui_password
