// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-playground/universal-translator"
	validator2 "github.com/go-playground/validator/v10"
	"github.com/jmoiron/sqlx"
	"github.com/vovancho/lingua-cat-go/exercise/domain"
	http2 "github.com/vovancho/lingua-cat-go/exercise/exercise/delivery/http"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/repository/grpc"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/repository/postgres"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/usecase"
	"github.com/vovancho/lingua-cat-go/exercise/internal/auth"
	"github.com/vovancho/lingua-cat-go/exercise/internal/config"
	"github.com/vovancho/lingua-cat-go/exercise/internal/db"
	"github.com/vovancho/lingua-cat-go/exercise/internal/response"
	"github.com/vovancho/lingua-cat-go/exercise/internal/translator"
	"github.com/vovancho/lingua-cat-go/exercise/internal/validator"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	utTranslator, err := translator.NewTranslator()
	if err != nil {
		return nil, err
	}
	validate, err := validator.NewValidator(utTranslator)
	if err != nil {
		return nil, err
	}
	publicKeyPath := ProvidePublicKeyPath(configConfig)
	authService, err := auth.NewAuthService(publicKeyPath)
	if err != nil {
		return nil, err
	}
	dsn := ProvideDSN(configConfig)
	sqlxDB, err := db.NewDB(dsn)
	if err != nil {
		return nil, err
	}
	dbDB := getPostgresDB(sqlxDB)
	exerciseRepository := postgres.NewPostgresExerciseRepository(dbDB)
	timeout := ProvideUseCaseTimeout(configConfig)
	exerciseUseCase := usecase.NewExerciseUseCase(exerciseRepository, validate, timeout)
	taskRepository := postgres.NewPostgresTaskRepository(dbDB)
	dictionaryRepository := grpc.NewPostgresDictionaryRepository()
	taskUseCase := usecase.NewTaskUseCase(taskRepository, dictionaryRepository, validate, timeout)
	server := newHTTPServer(configConfig, validate, utTranslator, authService, exerciseUseCase, taskUseCase)
	app := NewApp(configConfig, server, sqlxDB)
	return app, nil
}

// wire.go:

// App представляет приложение с конфигурацией и серверами
type App struct {
	Config     *config.Config
	HTTPServer *http.Server
	DB         *sqlx.DB
}

// NewApp создаёт новый экземпляр App
func NewApp(cfg *config.Config, httpServer *http.Server, db2 *sqlx.DB) *App {
	return &App{
		Config:     cfg,
		HTTPServer: httpServer,
		DB:         db2,
	}
}

func ProvideDSN(cfg *config.Config) db.DSN {
	return db.DSN(cfg.DBDSN)
}

func ProvidePublicKeyPath(cfg *config.Config) auth.PublicKeyPath {
	return auth.PublicKeyPath(cfg.AuthPublicKeyPath)
}

// getPostgresDB возвращает *sqlx.DB как db.DB
func getPostgresDB(db2 *sqlx.DB) db.DB {
	return db2
}

// getUseCaseTimeout возвращает таймаут для use case из конфигурации
func ProvideUseCaseTimeout(cfg *config.Config) usecase.Timeout {
	return usecase.Timeout(time.Duration(cfg.Timeout) * time.Second)
}

// newHTTPServer создаёт новый HTTP-сервер
func newHTTPServer(
	cfg *config.Config,
	validate *validator2.Validate,
	trans ut.Translator,
	authService *auth.AuthService,
	exerciseUcase domain.ExerciseUseCase,
	taskUcase domain.TaskUseCase,
) *http.Server {
	router := http.NewServeMux()
	http2.NewExerciseHandler(router, validate, authService, exerciseUcase)
	http2.NewTaskHandler(router, validate, taskUcase)
	return &http.Server{
		Addr:    cfg.HTTPPort,
		Handler: response.ErrorMiddleware(authService.AuthMiddleware(router), trans),
	}
}
