// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ThreeDotsLabs/watermill"
	"github.com/ThreeDotsLabs/watermill-kafka/v3/pkg/kafka"
	"github.com/ThreeDotsLabs/watermill-sql/v3/pkg/sql"
	"github.com/ThreeDotsLabs/watermill/message"
	"github.com/go-playground/universal-translator"
	validator2 "github.com/go-playground/validator/v10"
	"github.com/jmoiron/sqlx"
	"github.com/vovancho/lingua-cat-go/exercise/domain"
	http2 "github.com/vovancho/lingua-cat-go/exercise/exercise/delivery/http"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/repository/grpc"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/repository/postgres"
	"github.com/vovancho/lingua-cat-go/exercise/exercise/usecase"
	"github.com/vovancho/lingua-cat-go/exercise/internal/config"
	"github.com/vovancho/lingua-cat-go/exercise/internal/db"
	"github.com/vovancho/lingua-cat-go/exercise/internal/response"
	"github.com/vovancho/lingua-cat-go/exercise/internal/tracing"
	"github.com/vovancho/lingua-cat-go/exercise/internal/translator"
	"github.com/vovancho/lingua-cat-go/exercise/internal/validator"
	"github.com/vovancho/lingua-cat-go/pkg/auth"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel/sdk/trace"
	grpc2 "google.golang.org/grpc"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	utTranslator, err := translator.NewTranslator()
	if err != nil {
		return nil, err
	}
	validate, err := validator.NewValidator(utTranslator)
	if err != nil {
		return nil, err
	}
	publicKeyPath := ProvidePublicKeyPath(configConfig)
	authService, err := auth.NewAuthService(publicKeyPath)
	if err != nil {
		return nil, err
	}
	dsn := ProvideDSN(configConfig)
	sqlxDB, err := db.NewDB(dsn)
	if err != nil {
		return nil, err
	}
	dbDB := getPostgresDB(sqlxDB)
	exerciseRepository := postgres.NewPostgresExerciseRepository(dbDB)
	timeout := ProvideUseCaseTimeout(configConfig)
	exerciseUseCase := usecase.NewExerciseUseCase(exerciseRepository, validate, timeout)
	clientConn, err := ProvideGRPCConn(configConfig)
	if err != nil {
		return nil, err
	}
	dictionaryRepository := grpc.NewGrpcDictionaryRepository(clientConn, authService)
	dictionaryUseCase := usecase.NewDictionaryUseCase(dictionaryRepository, validate, timeout)
	taskRepository := postgres.NewPostgresTaskRepository(dbDB)
	exerciseCompletedTopic := ProvideKafkaExerciseCompletedTopic(configConfig)
	taskUseCase := usecase.NewTaskUseCase(exerciseUseCase, dictionaryUseCase, taskRepository, validate, timeout, exerciseCompletedTopic)
	server := newHTTPServer(configConfig, validate, utTranslator, authService, exerciseUseCase, taskUseCase)
	loggerAdapter := ProvideLogger()
	subscriber, err := ProvideSubscriber(sqlxDB, loggerAdapter)
	if err != nil {
		return nil, err
	}
	publisher, err := ProvidePublisher(configConfig, loggerAdapter)
	if err != nil {
		return nil, err
	}
	router, err := ProvideOutboxRouter(loggerAdapter, subscriber, publisher, configConfig)
	if err != nil {
		return nil, err
	}
	serviceName := ProvideServiceName(configConfig)
	endpoint := ProvideTracingEndpoint(configConfig)
	tracerProvider, err := tracing.NewTracer(serviceName, endpoint)
	if err != nil {
		return nil, err
	}
	app := NewApp(configConfig, server, sqlxDB, router, tracerProvider)
	return app, nil
}

// wire.go:

// App представляет приложение с конфигурацией и серверами
type App struct {
	Config     *config.Config
	HTTPServer *http.Server
	DB         *sqlx.DB
	Outbox     *message.Router
	Tracer     *trace.TracerProvider
}

// NewApp создаёт новый экземпляр App
func NewApp(
	cfg *config.Config,
	httpServer *http.Server, db2 *sqlx.DB,
	outbox *message.Router,
	tracer *trace.TracerProvider,
) *App {
	return &App{
		Config:     cfg,
		HTTPServer: httpServer,
		DB:         db2,
		Outbox:     outbox,
		Tracer:     tracer,
	}
}

func ProvideServiceName(cfg *config.Config) config.ServiceName {
	return cfg.ServiceName
}

func ProvideDSN(cfg *config.Config) db.DSN {
	return db.DSN(cfg.DBDSN)
}

func ProvidePublicKeyPath(cfg *config.Config) auth.PublicKeyPath {
	return auth.PublicKeyPath(cfg.AuthPublicKeyPath)
}

// getPostgresDB возвращает *sqlx.DB как db.DB
func getPostgresDB(db2 *sqlx.DB) db.DB {
	return db2
}

// getUseCaseTimeout возвращает таймаут для use case из конфигурации
func ProvideUseCaseTimeout(cfg *config.Config) usecase.Timeout {
	return usecase.Timeout(time.Duration(cfg.Timeout) * time.Second)
}

func ProvideTracingEndpoint(cfg *config.Config) tracing.Endpoint {
	return tracing.Endpoint(cfg.JaegerCollectorEndpoint)
}

func ProvideGRPCConn(cfg *config.Config) (*grpc2.ClientConn, error) {
	conn, err := grpc2.Dial(cfg.DictionaryGRPCAddress, grpc2.WithInsecure(), grpc2.WithUnaryInterceptor(otelgrpc.UnaryClientInterceptor()), grpc2.WithStreamInterceptor(otelgrpc.StreamClientInterceptor()))
	if err != nil {
		return nil, err
	}
	return conn, nil
}

// newHTTPServer создаёт новый HTTP-сервер
func newHTTPServer(
	cfg *config.Config,
	validate *validator2.Validate,
	trans ut.Translator,
	authService *auth.AuthService,
	exerciseUcase domain.ExerciseUseCase,
	taskUcase domain.TaskUseCase,
) *http.Server {
	router := http.NewServeMux()
	http2.NewExerciseHandler(router, validate, authService, exerciseUcase)
	http2.NewTaskHandler(router, validate, authService, taskUcase, exerciseUcase)

	mainMux := http.NewServeMux()
	mainMux.Handle("/swagger.json", http.FileServer(http.Dir("doc")))
	mainMux.Handle("/", response.ErrorMiddleware(authService.AuthMiddleware(otelhttp.NewHandler(router, "exercise-http")), trans))

	return &http.Server{
		Addr:    cfg.HTTPPort,
		Handler: mainMux,
	}
}

// ProvideKafkaExerciseCompletedTopic возвращает имя топика о выполненных упражнениях
func ProvideKafkaExerciseCompletedTopic(cfg *config.Config) usecase.ExerciseCompletedTopic {
	return usecase.ExerciseCompletedTopic(cfg.KafkaExerciseCompletedTopic)
}

// ProvideLogger создает Watermill логгер
func ProvideLogger() watermill.LoggerAdapter {

	return watermill.NopLogger{}
}

// ProvideSubscriber создает SQL-подписчик
func ProvideSubscriber(db2 *sqlx.DB, logger watermill.LoggerAdapter) (message.Subscriber, error) {
	return sql.NewSubscriber(db2, sql.SubscriberConfig{
		SchemaAdapter:    sql.DefaultPostgreSQLSchema{},
		OffsetsAdapter:   sql.DefaultPostgreSQLOffsetsAdapter{},
		InitializeSchema: false,
	}, logger,
	)
}

// ProvidePublisher создает Kafka-паблишер
func ProvidePublisher(cfg *config.Config, logger watermill.LoggerAdapter) (message.Publisher, error) {
	return kafka.NewPublisher(kafka.PublisherConfig{
		Brokers:   []string{cfg.KafkaBroker},
		Marshaler: kafka.DefaultMarshaler{},
	}, logger,
	)
}

// ProvideOutboxRouter создает outbox роутер из БД ProvideSubscriber в ProvidePublisher
func ProvideOutboxRouter(
	logger watermill.LoggerAdapter,
	subscriber message.Subscriber,
	publisher message.Publisher,
	cfg *config.Config,
) (*message.Router, error) {
	router, err := message.NewRouter(message.RouterConfig{}, logger)
	if err != nil {
		return nil, err
	}

	router.AddNoPublisherHandler(
		"outbox_to_kafka",
		cfg.KafkaExerciseCompletedTopic,
		subscriber,
		func(msg *message.Message) error {
			return publisher.Publish(cfg.KafkaExerciseCompletedTopic, msg)
		},
	)

	return router, nil
}
