services:
    lcg-dictionary-backend:
        image: golang:1.24-alpine3.21
        volumes:
            - ./:/app
            - dictionary-backend-pkg-mod:/go/pkg/mod
        working_dir: /app
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-dictionary-backend.entrypoints=web
            - traefik.http.routers.lcg-dictionary-backend.service=lcg-dictionary-backend
            - traefik.http.routers.lcg-dictionary-backend.rule=Host(`api.lingua-cat-go.localhost`) && PathPrefix(`/dictionary/`)
            - traefik.http.routers.lcg-dictionary-backend.middlewares=strip-dictionary-prefix
            - traefik.http.middlewares.strip-dictionary-prefix.stripprefix.prefixes=/dictionary
            - traefik.http.services.lcg-dictionary-backend.loadbalancer.server.port=80
            - traefik.tcp.routers.lcg-dictionary-grpc.entrypoints=dictionary-grpc
            - traefik.tcp.routers.lcg-dictionary-grpc.service=lcg-dictionary-grpc
            - traefik.tcp.routers.lcg-dictionary-grpc.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-dictionary-grpc.loadbalancer.server.port=50051
        command: sh -c "go build -o /tmp/main app/main.go && exec /tmp/main"
        depends_on:
            - lcg-dictionary-db

    lcg-dictionary-db:
        image: postgres:17.2-alpine
        environment:
            POSTGRES_USER: dictionary
            POSTGRES_PASSWORD_FILE: /run/secrets/dictionary_db_password
            POSTGRES_DB: dictionary
        volumes:
            - dictionary-db:/var/lib/postgresql/data
        secrets:
            - dictionary_db_password
        labels:
            - traefik.enable=true
            - traefik.tcp.routers.lcg-dictionary-db.entrypoints=postgres
            - traefik.tcp.routers.lcg-dictionary-db.service=lcg-dictionary-db
            - traefik.tcp.routers.lcg-dictionary-db.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-dictionary-db.loadbalancer.server.port=5432
volumes:
    dictionary-db:
    dictionary-backend-pkg-mod:
