services:
    lcg-exercise-backend:
        image: golang:1.24-alpine3.21
        volumes:
            - ./:/app
            - exercise-backend-pkg-mod:/go/pkg/mod
        working_dir: /app
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-exercise-backend.entrypoints=web
            - traefik.http.routers.lcg-exercise-backend.service=lcg-exercise-backend
            - traefik.http.routers.lcg-exercise-backend.rule=Host(`api.lingua-cat-go.localhost`) && PathPrefix(`/exercise/`)
            - traefik.http.routers.lcg-exercise-backend.middlewares=strip-exercise-prefix
            - traefik.http.middlewares.strip-exercise-prefix.stripprefix.prefixes=/exercise
            - traefik.http.services.lcg-exercise-backend.loadbalancer.server.port=80
        command: sh -c "go build -o /tmp/main app/main.go && exec /tmp/main"
        depends_on:
            - lcg-exercise-db

    lcg-exercise-db:
        image: postgres:17.2-alpine
        environment:
            POSTGRES_USER: exercise
            POSTGRES_PASSWORD_FILE: /run/secrets/exercise_db_password
            POSTGRES_DB: exercise
        volumes:
            - exercise-db:/var/lib/postgresql/data
        secrets:
            - exercise_db_password
        labels:
            - traefik.enable=true
            - traefik.tcp.routers.lcg-exercise-db.entrypoints=exercise-db
            - traefik.tcp.routers.lcg-exercise-db.service=lcg-exercise-db
            - traefik.tcp.routers.lcg-exercise-db.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-exercise-db.loadbalancer.server.port=5432
volumes:
    exercise-db:
    exercise-backend-pkg-mod:
