services:
    lcg-analytics-backend:
        image: golang:1.24-alpine3.21
        environment:
            AUTH_PUBLIC_KEY_PATH: /run/secrets/auth_public_key
        volumes:
            - ./:/app
            - ../pkg:/pkg:/pkg
            - analytics-backend-pkg-mod:/go/pkg/mod
        secrets:
            - auth_public_key
        working_dir: /app
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-analytics-backend.entrypoints=web
            - traefik.http.routers.lcg-analytics-backend.service=lcg-analytics-backend
            - traefik.http.routers.lcg-analytics-backend.rule=Host(`api.lingua-cat-go.localhost`) && PathPrefix(`/analytics/`)
            - traefik.http.routers.lcg-analytics-backend.middlewares=strip-analytics-prefix,cors
            - traefik.http.middlewares.strip-analytics-prefix.stripprefix.prefixes=/analytics
            - traefik.http.services.lcg-analytics-backend.loadbalancer.server.port=80
        command: sh -c "sleep 2 && go build -o /tmp/main cmd/main.go && exec /tmp/main"
        depends_on:
            lcg-kafka:
                condition: service_healthy
            lcg-analytics-db:
                condition: service_healthy
            lcg-keycloak:
                condition: service_started
            lcg-jaeger:
                condition: service_started

    lcg-analytics-db:
        image: clickhouse/clickhouse-server:25.4-alpine
        environment:
            CLICKHOUSE_USER: analytics
            CLICKHOUSE_PASSWORD_FILE: /run/secrets/analytics_db_password
            CLICKHOUSE_DB: analytics
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        healthcheck:
            test: ["CMD-SHELL", "wget --spider -q http://lcg-analytics-db:8123/ping || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - analytics-db:/var/lib/clickhouse
        secrets:
            - analytics_db_password
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-analytics-db.entrypoints=web
            - traefik.http.routers.lcg-analytics-db.service=lcg-analytics-db
            - traefik.http.routers.lcg-analytics-db.rule=Host(`analytics-db.lingua-cat-go.localhost`)
            - traefik.http.services.lcg-analytics-db.loadbalancer.server.port=8123
            - traefik.tcp.routers.lcg-analytics-db-tcp.entrypoints=analytics-db
            - traefik.tcp.routers.lcg-analytics-db-tcp.service=lcg-analytics-db-tcp
            - traefik.tcp.routers.lcg-analytics-db-tcp.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-analytics-db-tcp.loadbalancer.server.port=9000

volumes:
    analytics-db:
    analytics-backend-pkg-mod:
