services:
    lcg-analytics-backend:
        image: golang:1.24-alpine3.21
        volumes:
            - ./:/app
            - analytics-backend-pkg-mod:/go/pkg/mod
        working_dir: /app
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-analytics-backend.entrypoints=web
            - traefik.http.routers.lcg-analytics-backend.service=lcg-analytics-backend
            - traefik.http.routers.lcg-analytics-backend.rule=Host(`api.lingua-cat-go.localhost`) && PathPrefix(`/analytics/`)
            - traefik.http.routers.lcg-analytics-backend.middlewares=strip-analytics-prefix
            - traefik.http.middlewares.strip-analytics-prefix.stripprefix.prefixes=/analytics
            - traefik.http.services.lcg-analytics-backend.loadbalancer.server.port=80
        command: sh -c "go build -o /tmp/main app/main.go && exec /tmp/main"
#        command: sh -c "go build -o /tmp/main app/consumer.go && exec /tmp/main"
        depends_on:
            - lcg-analytics-db

    lcg-analytics-db:
        image: clickhouse/clickhouse-server:25.4-alpine
        environment:
            CLICKHOUSE_USER: analytics
            CLICKHOUSE_PASSWORD_FILE: /run/secrets/analytics_db_password
            CLICKHOUSE_DB: analytics
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        volumes:
            - analytics-db:/var/lib/clickhouse
        secrets:
            - analytics_db_password
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-analytics-db.entrypoints=web
            - traefik.http.routers.lcg-analytics-db.service=lcg-analytics-db
            - traefik.http.routers.lcg-analytics-db.rule=Host(`analytics-db.lingua-cat-go.localhost`)
            - traefik.http.services.lcg-analytics-db.loadbalancer.server.port=8123
            - traefik.tcp.routers.lcg-analytics-db-tcp.entrypoints=analytics-db
            - traefik.tcp.routers.lcg-analytics-db-tcp.service=lcg-analytics-db-tcp
            - traefik.tcp.routers.lcg-analytics-db-tcp.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-analytics-db-tcp.loadbalancer.server.port=9000

volumes:
    analytics-db:
    analytics-backend-pkg-mod:
