services:
    lcg-keycloak-postgresql:
        image: postgres:17.2-alpine
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD_FILE: /run/secrets/keycloak_db_password
            POSTGRES_DB: keycloak
        volumes:
            - keycloak-postgres:/var/lib/postgresql/data
        secrets:
            - keycloak_db_password
        labels:
            - traefik.enable=true
            - traefik.http.routers.keycloak-postgres.rule=Host(`keycloak-postgres.localhost`)
            - traefik.http.routers.keycloak-postgres.entryPoints=web
            - traefik.http.services.keycloak-postgres.loadbalancer.server.port=5432
            
    lcg-keycloak:
        image: quay.io/keycloak/keycloak:26.0
        environment:
            KC_DB: postgres
            KC_DB_URL_HOST: lcg-keycloak-postgresql
            KC_DB_URL_DATABASE: keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: secret
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_PORT: 80
#            KC_LOG_LEVEL: ALL
        volumes:
            - ./keycloak-export:/tmp/keycloak-export
        depends_on:
            - lcg-keycloak-postgresql
        command: start-dev
        labels:
            - traefik.enable=true
            - traefik.http.routers.keycloak.entrypoints=web
            - traefik.http.routers.keycloak.rule=Host(`keycloak.lingua-cat-go.localhost`)
            - traefik.http.services.keycloak.loadbalancer.server.port=80

volumes:
    keycloak-postgres:
