services:
    lcg-api-debug:
        build:
            dockerfile: docker/go-debug/Dockerfile
        volumes:
            - ./:/app
        labels:
            - traefik.enable=true
            - traefik.http.routers.lcg-api.entrypoints=web
            - traefik.http.routers.lcg-api.service=lcg-api
            - traefik.http.routers.lcg-api.rule=Host(`api.lingua-cat-go.localhost`)
            - traefik.http.services.lcg-api.loadbalancer.server.port=80
            - traefik.tcp.routers.lcg-api-debug.entrypoints=web-debug
            - traefik.tcp.routers.lcg-api-debug.rule=HostSNI(`*`)
            - traefik.tcp.services.lcg-api-debug.loadbalancer.server.port=2345
